name: instant
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.3.1+1
  firebase_database: ^2.0.2
  firebase_auth: ^0.8.3
  google_sign_in: ^4.0.1+1
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_launcher_icons: ^0.7.0

flutter_icons:
  android: ic_launcher
  ios: true
  image_path: assets/icon.png

flutter:
  uses-material-design: true
  assets:
    - assets/
